import Users.Athlete;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;

public class GUI extends javax.swing.JDialog
{

    /**
     * Creates new form GUI
     */
    public GUI(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiTabs = new javax.swing.JTabbedPane();
        mainMenuP = new javax.swing.JPanel();
        athlManagB = new javax.swing.JButton();
        subManagB = new javax.swing.JButton();
        resManagB = new javax.swing.JButton();
        athlManagP = new javax.swing.JPanel();
        athlButtonsP = new javax.swing.JPanel();
        registB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        athlBackB = new javax.swing.JButton();
        infoSP = new javax.swing.JScrollPane();
        infoT = new javax.swing.JTable();
        infoP = new javax.swing.JPanel();
        codeTF = new javax.swing.JTextField();
        contInfoL = new javax.swing.JLabel();
        dateOfBirthTF = new javax.swing.JTextField();
        ganderL = new javax.swing.JLabel();
        firstNameL = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        firstNameTF = new javax.swing.JTextField();
        dateOfBirthL = new javax.swing.JLabel();
        lastNameL = new javax.swing.JLabel();
        codeL = new javax.swing.JLabel();
        contInfoTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        femaleRB = new javax.swing.JRadioButton();
        subManagP = new javax.swing.JPanel();
        subBackB = new javax.swing.JButton();
        resManagP = new javax.swing.JPanel();
        resBackB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sports Academy Management");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiTabs.setPreferredSize(new java.awt.Dimension(900, 450));

        mainMenuP.setPreferredSize(new java.awt.Dimension(797, 300));
        mainMenuP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        athlManagB.setText("Athlete Management");
        athlManagB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athlManagBActionPerformed(evt);
            }
        });
        mainMenuP.add(athlManagB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        subManagB.setText("Subscription Management");
        subManagB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subManagB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subManagBActionPerformed(evt);
            }
        });
        mainMenuP.add(subManagB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        resManagB.setText("Reservation Management");
        resManagB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resManagB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resManagBActionPerformed(evt);
            }
        });
        mainMenuP.add(resManagB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        guiTabs.addTab("Main Menu", mainMenuP);

        registB.setText("Register");
        registB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registBActionPerformed(evt);
            }
        });

        updateB.setText("Update");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        athlBackB.setText("Back");
        athlBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athlBackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout athlButtonsPLayout = new javax.swing.GroupLayout(athlButtonsP);
        athlButtonsP.setLayout(athlButtonsPLayout);
        athlButtonsPLayout.setHorizontalGroup(
            athlButtonsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athlButtonsPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registB)
                .addGap(81, 81, 81)
                .addComponent(updateB)
                .addGap(85, 85, 85)
                .addComponent(deleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(athlBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        athlButtonsPLayout.setVerticalGroup(
            athlButtonsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athlButtonsPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(athlButtonsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registB)
                    .addComponent(updateB)
                    .addComponent(deleteB)
                    .addComponent(athlBackB))
                .addContainerGap())
        );

        infoT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "First Name", "Last Name", "Gender", "Date Of Birth", "Contact Information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoT.setColumnSelectionAllowed(true);
        infoSP.setViewportView(infoT);
        infoT.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        infoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTFActionPerformed(evt);
            }
        });
        infoP.add(codeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 238, -1));

        contInfoL.setText("Contact Information:");
        infoP.add(contInfoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, -1, -1));

        dateOfBirthTF.setText("dd/mm/yyyy");
        dateOfBirthTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateOfBirthTFMouseClicked(evt);
            }
        });
        dateOfBirthTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthTFActionPerformed(evt);
            }
        });
        dateOfBirthTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateOfBirthTFKeyTyped(evt);
            }
        });
        infoP.add(dateOfBirthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 238, -1));

        ganderL.setText("Gender:");
        infoP.add(ganderL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, 111, -1));

        firstNameL.setText("First Name:");
        infoP.add(firstNameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, 111, -1));

        maleRB.setText("Male");
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });
        infoP.add(maleRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 65, -1));

        firstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTFActionPerformed(evt);
            }
        });
        firstNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTFKeyTyped(evt);
            }
        });
        infoP.add(firstNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 238, -1));

        dateOfBirthL.setText("Date Of Birth:");
        infoP.add(dateOfBirthL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, 111, -1));

        lastNameL.setText("Last Name:");
        infoP.add(lastNameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 111, -1));

        codeL.setText("Code:");
        infoP.add(codeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 84, -1));

        contInfoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contInfoTFActionPerformed(evt);
            }
        });
        contInfoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contInfoTFKeyTyped(evt);
            }
        });
        infoP.add(contInfoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 238, -1));

        lastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTFActionPerformed(evt);
            }
        });
        lastNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTFKeyTyped(evt);
            }
        });
        infoP.add(lastNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 238, -1));

        femaleRB.setText("Female");
        femaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRBActionPerformed(evt);
            }
        });
        infoP.add(femaleRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        javax.swing.GroupLayout athlManagPLayout = new javax.swing.GroupLayout(athlManagP);
        athlManagP.setLayout(athlManagPLayout);
        athlManagPLayout.setHorizontalGroup(
            athlManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athlManagPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(athlManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(athlManagPLayout.createSequentialGroup()
                        .addComponent(athlButtonsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(athlManagPLayout.createSequentialGroup()
                        .addComponent(infoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoP, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        athlManagPLayout.setVerticalGroup(
            athlManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athlManagPLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(athlManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoSP, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(infoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(athlButtonsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        guiTabs.addTab("Athletes", athlManagP);

        subBackB.setText("Back");
        subBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subManagPLayout = new javax.swing.GroupLayout(subManagP);
        subManagP.setLayout(subManagPLayout);
        subManagPLayout.setHorizontalGroup(
            subManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subManagPLayout.createSequentialGroup()
                .addContainerGap(763, Short.MAX_VALUE)
                .addComponent(subBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        subManagPLayout.setVerticalGroup(
            subManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subManagPLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(subBackB)
                .addGap(14, 14, 14))
        );

        guiTabs.addTab("Subscriptions", subManagP);

        resBackB.setText("Back");
        resBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resManagPLayout = new javax.swing.GroupLayout(resManagP);
        resManagP.setLayout(resManagPLayout);
        resManagPLayout.setHorizontalGroup(
            resManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resManagPLayout.createSequentialGroup()
                .addContainerGap(763, Short.MAX_VALUE)
                .addComponent(resBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        resManagPLayout.setVerticalGroup(
            resManagPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resManagPLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(resBackB)
                .addGap(14, 14, 14))
        );

        guiTabs.addTab("Reservations", resManagP);

        getContentPane().add(guiTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -44, 910, 430));
        guiTabs.getAccessibleContext().setAccessibleName("mainMenu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    private void BackButton()
    {
        guiTabs.setSelectedIndex(0);
    }

    //Check if date of birth is a valid date
    private boolean CheckDate()
    {
        boolean validDate = false;

        String date = dateOfBirthTF.getText();
        if (date.length() != 10)
        {
            dateOfBirthTF.setText(null);
            return validDate;
        }

        //Break date to sub strings to check validity
        char slash1 = date.charAt(2);
        char slash2 = date.charAt(5);
        String dayS = date.substring(0,2);
        String monthS = date.substring(3,5);
        String yearS = date.substring(6);

        //Convert strings to int to compare dates
        int daysInt = Integer.parseInt(dayS);
        int monthInt = Integer.parseInt(monthS);
        int yearInt = Integer.parseInt(yearS);

        //Check date(accounts for leap years)
        if(slash1 != '/' || slash2 != '/' || (monthInt == 2 && ((yearInt % 4 == 0 && daysInt > 29) || (yearInt % 4 != 0 && daysInt > 28))) || daysInt > 31 || monthInt > 12 || yearInt < 1940 || yearInt > 2024)
        {
            dateOfBirthTF.setText(null);
        }
        else
        {
            validDate = true;
        }

        return validDate;
    }


    ///////////////////////////////////////////////////////////////////////////////////
    //                        Athlete Management Section                             //
    ///////////////////////////////////////////////////////////////////////////////////

    // A default model for the table that displays athlete info
    private DefaultTableModel athlModel = new DefaultTableModel();
    private ArrayList<Athlete> Athletes = new ArrayList<Athlete>();
    private String gender;


    private void athlManagBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_athlManagBActionPerformed
        guiTabs.setSelectedIndex(1);
    }//GEN-LAST:event_athlManagBActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_maleRBActionPerformed
        femaleRB.setSelected(false);
        gender = "Male";
    }//GEN-LAST:event_maleRBActionPerformed

    private void femaleRBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_femaleRBActionPerformed
        maleRB.setSelected(false);
        gender = "Female";
    }//GEN-LAST:event_femaleRBActionPerformed

    private void athlBackBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_backBActionPerformed
        BackButton();
    }//GEN-LAST:event_backBActionPerformed

    private void dateOfBirthTFActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_dateOfBirthTFActionPerformed

    }//GEN-LAST:event_dateOfBirthTFActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_deleteBActionPerformed
        athlModel = (DefaultTableModel) infoT.getModel();
        athlModel.removeRow(infoT.getSelectedRow());
    }//GEN-LAST:event_deleteBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_updateBActionPerformed
         int row = infoT.getSelectedRow();

         if (codeTF.getText() != null)
         {
             infoT.getModel().setValueAt(codeTF.getText(), row, 0);
         }

        if (firstNameTF.getText() != null)
        {
            infoT.getModel().setValueAt(firstNameTF.getText(), row, 1);
        }

        if (lastNameTF.getText() != null)
        {
            infoT.getModel().setValueAt(lastNameTF.getText(), row, 2);
        }

        if (dateOfBirthTF.getText() != null)
        {
            infoT.getModel().setValueAt(dateOfBirthTF.getText(), row, 4);
        }

        if (contInfoTF.getText() != null)
        {
            infoT.getModel().setValueAt(contInfoTF.getText(), row, 5);
        }

        infoT.getModel().setValueAt(gender, row, 3);


    }//GEN-LAST:event_updateBActionPerformed

    private void registBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_registBActionPerformed
        Athlete athl = new Athlete(firstNameTF.getText(), lastNameTF.getText(), gender, contInfoTF.getText(), dateOfBirthTF.getText(), Integer.parseInt(codeTF.getText()), false, 2);
        Athletes.add(athl);

        CheckDate();

        athlModel = (DefaultTableModel) infoT.getModel();
        athlModel.insertRow(0, new Object[]{codeTF.getText(), firstNameTF.getText(), lastNameTF.getText(), gender, dateOfBirthTF.getText(), contInfoTF.getText()});
    }//GEN-LAST:event_registBActionPerformed

    private void contInfoTFActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_contInfoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contInfoTFActionPerformed

    private void contInfoTFKeyTyped(java.awt.event.KeyEvent evt)
    {                                           

    }                                          

    private void lastNameTFActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_lastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTFActionPerformed

    private void lastNameTFKeyTyped(java.awt.event.KeyEvent evt)
    {//GEN-FIRST:event_lastNameTFKeyTyped
        char testChar = evt.getKeyChar();
        if(!Character.isAlphabetic(testChar))
        {
            evt.consume();
        }
    }//GEN-LAST:event_lastNameTFKeyTyped

    private void firstNameTFActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_firstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTFActionPerformed

    private void firstNameTFKeyTyped(java.awt.event.KeyEvent evt)
    {//GEN-FIRST:event_firstNameTFKeyTyped
        char testChar = evt.getKeyChar();
        if(!Character.isAlphabetic(testChar))
        {
            evt.consume();
        }
    }//GEN-LAST:event_firstNameTFKeyTyped

    private void codeTFActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_codeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTFActionPerformed

    private void dateOfBirthTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateOfBirthTFKeyTyped
        char testInt = evt.getKeyChar();
        if(!(Character.isDigit(testInt)) && (testInt != '/'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_dateOfBirthTFKeyTyped

    private void dateOfBirthTFMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_dateOfBirthTFMouseClicked
        dateOfBirthTF.setText("");
    }//GEN-LAST:event_dateOfBirthTFMouseClicked

    ///////////////////////////////////////////////////////////////////////////////////
    //                       Subscription Management Section                         //
    ///////////////////////////////////////////////////////////////////////////////////

    private void subManagBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_subManagBActionPerformed
        guiTabs.setSelectedIndex(2);
    }//GEN-LAST:event_subManagBActionPerformed

    private void subBackBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_subBackBActionPerformed
        BackButton();
    }//GEN-LAST:event_subBackBActionPerformed

    ///////////////////////////////////////////////////////////////////////////////////
    //                        Reservation Management Section                         //
    ///////////////////////////////////////////////////////////////////////////////////

    private void resManagBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_resManagBActionPerformed
        guiTabs.setSelectedIndex(3);
    }//GEN-LAST:event_resManagBActionPerformed

    private void resBackBActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_resBackBActionPerformed
        BackButton();
    }//GEN-LAST:event_resBackBActionPerformed








////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                GUI dialog = new GUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton athlBackB;
    private javax.swing.JPanel athlButtonsP;
    private javax.swing.JButton athlManagB;
    private javax.swing.JPanel athlManagP;
    private javax.swing.JLabel codeL;
    private javax.swing.JTextField codeTF;
    private javax.swing.JLabel contInfoL;
    private javax.swing.JTextField contInfoTF;
    private javax.swing.JLabel dateOfBirthL;
    private javax.swing.JTextField dateOfBirthTF;
    private javax.swing.JButton deleteB;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel firstNameL;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel ganderL;
    private javax.swing.JTabbedPane guiTabs;
    private javax.swing.JPanel infoP;
    private javax.swing.JScrollPane infoSP;
    private javax.swing.JTable infoT;
    private javax.swing.JLabel lastNameL;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JPanel mainMenuP;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JButton registB;
    private javax.swing.JButton resBackB;
    private javax.swing.JButton resManagB;
    private javax.swing.JPanel resManagP;
    private javax.swing.JButton subBackB;
    private javax.swing.JButton subManagB;
    private javax.swing.JPanel subManagP;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
